### ISSUE TITLE
dalao 今天看到您的餐厅作业 深感五体投地 但是有些地方我没看懂。。。。

### ISSUE THREAD

**Issue by lightyisu** [huizhc/day47#1]
能不能请教一下那个promise做菜那部分 做一道菜怎么在这道菜做完再计时呢

**Comment by huizhc** [comment]
https://www.cnblogs.com/richard1015/p/9155683.html，看看这个咯。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lightyisu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月31日(星期五) 上午10:56
收件人:&nbsp;"huizhc/day47"<day47@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[huizhc/day47] dalao 今天看到您的餐厅作业 深感五体投地 但是有些地方我没看懂。。。。 (#1)




能不能请教一下那个promise做菜那部分 做一道菜怎么在这道菜做完再计时呢

**Comment by lightyisu** [comment]
谢谢dalao 方便要个qq 或者有什么交流群嘛:) 最近还在学前端学院的 好多弄不懂 哭了 很多细节磨了几天也磨不出来 而且有的地方不太懂55 也没有人可以交流 感觉好无助(╥╯^╰╥) 不方便的也没事 我再自己看看哈哈

**Comment by huizhc** [comment]
加我qq吧1125133876，之前发给你过不知道你有没有收到。
